version: '2.1'

services:
  alpine:
    image: jumanjiman/xrdp:alpine
    build:
      context: alpine/
      args:
        CI_BUILD_URL: ${CIRCLE_BUILD_URL}
        BUILD_DATE:   ${BUILD_DATE}
        VCS_REF:      ${VCS_REF}
    pids_limit: 300
    cpu_shares: 1023
    mem_limit: 1G
    shm_size: 32M
    stdin_open: true
    tty: true
    ports:
      - "2389:3389"

  alpine_tag:
    extends: alpine
    image: jumanjiman/xrdp:${ALPINE_TAG}
